### PR TITLE
vmime: support multi-address Reply-To

### PR DESCRIPTION
**Pull request by jengelh**
RFC 5322 says Reply-To is an address list. Treat it as such.

### CODE REVIEW

**Comment by vincent-richard** [comment]
Hello!

Thanks for the suggestion, this is an issue indeed.
However, I see 2 problems with this:

* first, it breaks API: users currently expect the "Reply-To" field to have a value of type "mailboxField" (casts will fail);

* RFC says that "Reply-To:" is an address-list, so it should be the "addressList" class, like the "To:" field, not "mailboxList" (the difference is "addressList" can contain mailbox groups).

```
   reply-to        =   "Reply-To:" address-list CRLF
   to              =   "To:" address-list CRLF

```

**Comment by jengelh** [comment]
1. It is legal for dynamic_cast to return nullptr, and static checkers like Coverity-SCAN consider it a bug not to check the return value. While programs have nothing to do in that case (as they indeed do not check for the newer mailboxList)... maybe you have some idea. Handing out just the first field of the list if a list is cast to a single item?

2. The current vmime code, in `headerFieldFactory.cpp`, has the singular `Reply-To` defined as a "mailbox" (mailboxField) rather than an "address", so I thought you had a reason. I just added "-List"...

**Comment by jengelh** [comment]
Maybe it's ok to just go ahead with the break? There are other breaks since 0.9.2 like f173b0a5.

**Comment by jengelh** [comment]
Can this be moved forward somehow?

**Comment by vincent-richard** [comment]
Totally forgot about this.
Fixed with 3733af51.

**Comment by cmpalm** [comment]
Why did you pick addressList and not mailboxList (given it was a mailbox before, it should be a mailbox afterwards), and what is the difference between those two types?

**Comment by jengelh** [comment]
What remains unclear to me is, why did you (a) originally choose `mailbox` over `address`, (b) why now `addressList` rather than `mailboxList`?

**Comment by vincent-richard** [comment]
The reason I have "upgraded" it to an address[List] is that the [RFC-5322](https://tools.ietf.org/html/rfc5322) says so:

```
reply-to        =   "Reply-To:" address-list CRLF
to              =   "To:" address-list CRLF
...
address-list    =   (address *("," address)) / obs-addr-list
address         =   mailbox / group
``` 

An addressList can contain mailboxes and mailbox groups. A mailboxList can only contain mailboxes, which is not RFC-compliant. So it should always have been an addressList, but unfortunately I can't tell why it was a originally a mailbox in VMime...

**Pull request closed without merging**
