### PR TITLE
build: stop joining PREFIX to LIBDIR

### LINKED ISSUE #200: Installation chooses wrong path /usr/usr/lib
Situated on a9b822140bf8926620fd21b880893d4c214dd8c0, installation of the libvmime.so files goes into the wrong directory.:
```
[    7s] + /usr/bin/cmake /home/abuild/rpmbuild/BUILD/vmime-0.9.2.50/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules -DVMIME_SENDMAIL_PATH:STRING=/usr/sbin/sendmail -DVMIME_BUILD_SAMPLES:BOOL=OFF -DVMIME_HAVE_TLS_SUPPORT:BOOL=ON -DVMIME_BUILD_STATIC_LIBRARY:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo '-DCMAKE_CXX_FLAGS:STRING=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DVMIME_ALWAYS_GENERATE_7BIT_PARAMETER=1' '-DCMAKE_C_FLAGS:STRING=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DVMIME_ALWAYS_GENERATE_7BIT_PARAMETER=1'
...
[   45s] + DESTDIR=/home/abuild/rpmbuild/BUILDROOT/libvmime-0.9.2.50-0.x86_64
[   45s] + /usr/bin/make install -C build
[   46s] make: Entering directory '/home/abuild/rpmbuild/BUILD/vmime-0.9.2.50/build'
...
[   47s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/libvmime-0.9.2.50-0.x86_64/usr/usr/lib64/libvmime.so.1.0.0
[   47s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/libvmime-0.9.2.50-0.x86_64/usr/usr/lib64/libvmime.so.1
[   47s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/libvmime-0.9.2.50-0.x86_64/usr/usr/lib64/libvmime.so
[   47s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/libvmime-0.9.2.50-0.x86_64/usr/include/vmime/address.hpp
[   47s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/libvmime-0.9.2.50-0.x86_64/usr/include/vmime/addressList.hpp
[   47s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/libvmime-0.9.2.50-0.x86_64/usr/include/vmime/attachment.hpp
[   47s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/libvmime-0.9.2.50-0.x86_64/usr/include/vmime/attachmentHelper.hpp
```

### PR DESCRIPTION
**Pull request by jengelh**
Of the build systems I know, variables like libdir (whatever the name)
is never appended to prefix, because overrides are commonly an absolute
path and joining with prefix would lead to /usr/usr/lib.

Fixes #200.

### CODE REVIEW

**Comment by vincent-richard** [comment]
It seems `CMAKE_INSTALL_LIBDIR` can actually be either a relative or an absolute path (see the discussion here for example: https://bugzilla.redhat.com/show_bug.cgi?id=1301720 ).

Wouldn't be more safe to do something like this:

```
IF(IS_ABSOLUTE ${CMAKE_INSTALL_LIBDIR})
    SET(VMIME_INSTALL_LIBDIR ${CMAKE_INSTALL_LIBDIR})
ELSE()
    SET(VMIME_INSTALL_LIBDIR "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}")
ENDIF()
```

then using `VMIME_INSTALL_LIBDIR` instead of `CMAKE_INSTALL_LIBDIR` directly? This way we cover all cases, whether `CMAKE_INSTALL_LIBDIR` is an absolute path or not.

**Comment by jengelh** [comment]
Sure, why not.

**Comment by vincent-richard** [comment]
Could you please test the following patch to see if it now fixes your issue?
https://www.vmime.org/public/download/patches/vmime-20190628-prefix.patch

**Comment by jengelh** [comment]
Something is not quite working.
```
/usr/bin/cmake /home/abuild/rpmbuild/BUILD/vmime/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64
...
make install
...
./usr/lib
./usr/lib/libvmime.so.1.0.0
./usr/lib/pkgconfig
./usr/lib/pkgconfig/vmime.pc
./usr/lib/libvmime.so
./usr/lib/libvmime.so.1
```
so it seems to ignore my request for lib64.

**Comment by vincent-richard** [comment]
Don't know what exactly are `INCLUDE_INSTALL_DIR` and `LIB_INSTALL_DIR` variables, but if you try with `CMAKE_INSTALL_INCLUDEDIR` and `CMAKE_INSTALL_LIBDIR` it will work as expected:

    cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_INCLUDEDIR:PATH=/usr/include -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64

Also with the relative path version:

    cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_INCLUDEDIR:PATH=include -DCMAKE_INSTALL_LIBDIR:PATH=lib64

These are the "standard" directories set by the GNUInstallDirs package:
https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

**Comment by jengelh** [comment]
Did try the patch with just this command line, same issue:

```
rm -rf *; /usr/bin/cmake .. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64; make -j16; make install DESTDIR=$PWD/rtx

-- The C compiler identification is GNU 9.1.1
-- The CXX compiler identification is GNU 9.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at /usr/share/cmake/Modules/GenerateExportHeader.cmake:414 (message):
  The add_compiler_export_flags function is obsolete.  Use the
  CXX_VISIBILITY_PRESET and VISIBILITY_INLINES_HIDDEN target properties
  instead.
Call Stack (most recent call first):
  CMakeLists.txt:118 (ADD_COMPILER_EXPORT_FLAGS)


-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Build type: Debug
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for C++ include cstdint
-- Looking for C++ include cstdint - found
-- Check size of char
-- Check size of char - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of __int64
-- Check size of __int64 - failed
-- Check size of int64_t
-- Check size of int64_t - failed
-- Check size of size_t
-- Check size of size_t - done
-- Sendmail binary found at /usr/sbin/sendmail
-- Sendmail binary found at /usr/lib/sendmail
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libgsasl'
--   Found libgsasl, version 1.8.0
-- Found GSASL: /usr/lib64/libgsasl.so  
-- Found GnuTLS: /usr/lib64/libgnutls.so (found version "3.6.7") 
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1c")  
-- Looking for gnutls_priority_set_direct
-- Looking for gnutls_priority_set_direct - found
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib64/libc.so
-- Found ICU: /usr/lib64/libicuuc.so  
-- Looking for gmtime_s
-- Looking for gmtime_s - not found
-- Looking for gmtime_r
-- Looking for gmtime_r - found
-- Looking for localtime_s
-- Looking for localtime_s - not found
-- Looking for localtime_r
-- Looking for localtime_r - found
-- Looking for strcpy_s
-- Looking for strcpy_s - not found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for getnameinfo
-- Looking for getnameinfo - found
-- Looking for gettid
-- Looking for gettid - not found
-- Looking for syscall
-- Looking for syscall - found
-- Looking for SYS_gettid
-- Looking for SYS_gettid - found
-- Looking for getthrid
-- Looking for getthrid - not found
-- Looking for SO_KEEPALIVE
-- Looking for SO_KEEPALIVE - found
-- Looking for SO_NOSIGPIPE
-- Looking for SO_NOSIGPIPE - not found
-- Looking for MSG_NOSIGNAL
-- Looking for MSG_NOSIGNAL - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for getaddrinfo_a
-- Looking for getaddrinfo_a - found
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.15") found components:  doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jengelh/work/vmime/b
Scanning dependencies of target vmime
Scanning dependencies of target vmime-static
[  0%] Building CXX object CMakeFiles/vmime.dir/src/vmime/bodyPart.cpp.o
[...]
[100%] Linking CXX static library build/lib/libvmime.a
[100%] Built target vmime-static
[ 50%] Built target vmime
[100%] Built target vmime-static
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/jengelh/work/vmime/b/rtx/usr/lib/libvmime.so.1.0.0
[...]
-- Installing: /home/jengelh/work/vmime/b/rtx/usr/include/vmime/export-static.hpp
-- Installing: /home/jengelh/work/vmime/b/rtx/usr/cmake/vmime-config.cmake
-- Installing: /home/jengelh/work/vmime/b/rtx/usr/cmake/vmime-config-debug.cmake
-- Installing: /home/jengelh/work/vmime/b/rtx/usr/lib/pkgconfig/vmime.pc
```

/usr/lib is wrong (should be /usr/lib64 as requested), /usr/cmake is wrong (should be /usr/share/cmake).

**Comment by vincent-richard** [comment]
Hello again!

Thanks for the command line, which permitted to reproduce the problem. Actually, there was an override of the CMAKE_INSTALL_PREFIX variable somewhere.

Here is a new patch for you to test:
https://www.vmime.org/public/download/patches/vmime-20190702-prefix2.patch

Tested it with your command line, and it is working correctly. Except that the CMake package file ("vmime-config.cmake") is installed to {libdir}/cmake/vmime/, which should not be an issue as it is one of the standard locations tested by CMake FIND_PACKAGE() command.

**Comment by Thermi** [comment]
Was this or anything like it ever further tested?

**Comment by vincent-richard** [comment]
I didn't get any feedback on the patch from @jengelh, so you are welcome to test it.

**Comment by jengelh** [comment]
The patch from Jul 2 worked.

**Comment by jengelh** [comment]
In conjunction with the Jun 30 patch, I had added https://github.com/Kopano-dev/vmime/commit/8469a6279c4ed52308bfca594f03c9f356d770ea on top as a hack and I cannot recall any consideration for the Jul 2 patch.
From a cursory look, the Jul2 patch however does include 8469's line removal, so I guess it's fine.

**Pull request closed without merging**
